### ISSUE TITLE
Support for allowing specific static methods.

### ISSUE THREAD

**Issue by jglamine** [rfeie/eslint-plugin-ie-static-methods#1]
Thanks for making this plugin!

It would be awesome if you could add support for allowing specific methods. For example, I'm using a polyfill for Object.assign. So I want to allow that but not allow other methods like Array.from.

Let me know what you think!

**Comment by rfeie** [comment]
That sounds like a good enhancement. Should not be too hard to support. Will try to update over the  Thanksgiving holiday

**Comment by rfeie** [comment]
Version 1.1.0 should support your request. Let me know if you have any questions or issues.

**Comment by jglamine** [comment]
Perfect. Thanks for the quick turnaround on this, I really appreciate it!

**Comment by jglamine** [comment]
Can you publish this so that I can pull it in via npm?

**Comment by rfeie** [comment]
Apologies. Done!
